version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: discordbot_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  discord_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-bot-container
    depends_on:
      - database
    environment:
      DB_URL: jdbc:postgresql://database:5432/discordbot_db
      DB_USER: myuser
      DB_PASS: mypassword
      HIBERNATE_DDL: create-drop
      SQL_INIT_MODE: always
      BOT_TOKEN: ${BOT_TOKEN}
      TENOR_API_KEY: ${TENOR_API_KEY}
    ports:
      - "8080:8080"

volumes:
  postgres-data: